### ISSUE TITLE
Incorrect calculation of US income tax before credits

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1005]
Consider the following 2021 test case in which OpenFisca-US 0.85.1 version and TAXSIM35 agree on the AGI, agree on the itemized deduction amount, and therefore, agree on taxable income, which is $130,150.  But the two models disagree on the income tax liability before credits.  TAXSIM35 (and my US income Tax Analyzer and my hand calculation) gets a tax of $23,805 while OpenFisca-US gets a tax of $27,157.  The difference in tax before credits is $3352, which is the same as the difference in tax after all credits.  I don't understand how OpenFisca-US is calculating a tax of $27,157 based on taxable income of $130,150.

Here is the test case:
```
# OpenFisca-US test file derived from q21.its.csv and q21.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/18/22) With TCJA

- name: Tax unit with taxsimid 11991 from q21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 39
        employment_income: 160000
        social_security: 19000
        real_estate_taxes: 11000
        interest_expense: 36000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 11173.60
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 16150.00
    #adjusted_gross_income: 176150.00
    #taxable_income: 130150.00
    #cdcc: 0.00
    #non_refundable_ctc: 2000.00
    #refundable_ctc: 2000.00
    #eitc: 0.00
    income_tax: 21805.00
```

And here are the test results:
```
  Test 'Tax unit with taxsimid 11991 from q21.its.csv':
    income_tax@2021: [25157.] differs from 21805.0
      with an absolute margin [3352.] > 0.01
```
