### ISSUE TITLE
2021 MA SCB qualified income differences with TAXSIM35

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1031]
The 0.86.0 version, which added MA SCB logic, generates in some cases an SCB qualifying income that differs from that generated by TAXSIM35.  The differences seem to be caused by the way OpenFisca-US fills in Line 4 on the MA Schedule CB.

<img width="843" alt="Screen Shot 2022-07-03 at 8 23 51 AM" src="https://user-images.githubusercontent.com/12170745/177040914-adb568c0-0f9a-456f-b4fa-057d301e75fe.png">

The following test case illustrates the problem: that OpenFisca-US does not put on Line 4 the "Full amount of social security benefits received", but instead puts only the amount of social security benefits not included in **US** AGI.  MA AGI excludes **all** social security benefits, so that is why Line 4 says to put in the **full** amount of social security benefits.

```
- name: Tax unit with taxsimid 840 from q21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 65
        employment_income: 24000
        social_security: 23000
        real_estate_taxes: 20000
        interest_expense: 21000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 61
        employment_income: 62000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3]
        state_code: MA
  output:
    ma_income_tax: 3403.20
```
Here are the test results for this case:
```
  Test 'Tax unit with taxsimid 840 from q21.its.csv':
    ma_income_tax@2021: [2233.2] differs from 3403.199951171875
      with an absolute margin [1170.] > 0.01
```
Comparing trace output from the two models, shows that the MA income tax difference is caused solely by a difference in the SCB credit.

Using the trace output, we compare how the two models fill out Schedule CB:
```
      OF-US  TAXSIM
(L3)  86000   86000  [MA AGI]<sum of employment_income of head & spouse>
(L4)   3450   23000  [social security benefits not in MA AGI]
(L5)      0       0  [pension income not in MA AGI]
(L6)      0       0  [misc incl public assistance benefits not in MA AGI]
(L7)  89450  109000  [=(L3)+(L4)+(L5)+(L6)]
(L8)   1700    1700  [exemptions]
(L9)  87750  107300  [=((L7)-(L8)]
```
So, OpenFisca-US generates a qualifying income that this below the SCB eligibility threshold of $93,000, while TAXSIM35 generates a qualifying income that is greater than the threshold, and hence, concludes this tax unit is not eligible for a SCB credit.
