### ISSUE TITLE
2021 US CTC differences with TAXSIM35

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1032]
Using the 0.86.0 version, there are US income liability differences with TAXSIM35 caused by differences in the CTC and CDCC amounts.  

In the following test case, there are at least two differences.  First, the refundable CTC amounts are not the same.  And second, even if the CTC amounts were the same, there would be a difference in the income tax liability (perhaps caused by some problem in handling the CDCC, which was refundable in 2021).

Here is the test case followed by test results and discussion:
```
# OpenFisca-US test file derived from r21.its.csv and r21.ota.csv files

- name: Tax unit with taxsimid 82818 from r21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 56
        employment_income: 84000
        taxable_interest_income: 10000
        short_term_capital_gains: 6000
        long_term_capital_gains: 6000
        social_security: 14000
        real_estate_taxes: 21000
        interest_expense: 35000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 10000
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: TX
  output:
    taxsim_tfica: 6426.00
    income_tax: -8776.00
```

Here are the test results:
```
  Test 'Tax unit with taxsimid 82818 from r21.its.csv':
    income_tax@2021: [-13776.] differs from -8776.0
      with an absolute margin [5000.] > 0.01
```

Trace output from the two models, show that they agree on AGI, taxable income, and income tax before credits (117,900 and 72,900 and 9914), but disagree on the CTC (11,730 in TAXSIM35 vs 12,000 for OpenFisca-US).  The trace output shows both the models agree that this tax unit gets a 5000 CDCC and a 1960 RRC.  All three credits are refundable in 2021, so the high-level summary for the two models looks like this:
```
-----------------------------
       TAXSIM   OpenFisca-US
-----------------------------
taxbc    9914           9914
-CTC    11730          12000
-CDCC    5000           5000
-RRC     1960           1960
-----------------------------
itax    -8776          -9046
```
But, for some reason, OpenFisca-US generates an income tax liability of -13,776 (not -9046).  I don't understand why that is so, but I'm nervous about the following trace output:
```
income_tax_before_credits<2021> >> [9914.]
elderly_disabled_credit<2021> >> [0.]
cdcc<2021> >> [5000.]
non_refundable_ctc<2021> >> [-270.]
income_tax_non_refundable_credits<2021> >> [4730.]
income_tax_capped_non_refundable_credits<2021> >> [4730.]
income_tax_before_refundable_credits<2021> >> [5184.]
refundable_ctc<2021> >> [12000.]
eitc<2021> >> [0.]
rrc_arpa<2021> >> [1960.]
income_tax<2021> >> [-13776.]
```
Both the CTC and CDCC are completely refundable in 2021, so I don't understand why there is a positive amount for nonrefundable credits.

Next, a discussion of the CTC difference.  Below I show part of the 2021 Schedule 8812 and the Schedule 8812 Line 5 Worksheet, and then I show how TAXSIM35 fills in the Worksheet for this test case to get the 11,730 CTC amount (which differs from the 12,000 generated by OpenFisca-US).

<img width="736" alt="Screen Shot 2022-07-03 at 10 50 35 AM" src="https://user-images.githubusercontent.com/12170745/177046894-de1f404b-b624-4d3b-bbb5-8908caea5875.png">

<img width="932" alt="Screen Shot 2022-07-03 at 10 43 21 AM" src="https://user-images.githubusercontent.com/12170745/177046922-5a998f4e-9692-43cd-a831-bcd52e0797d7.png">

```
Schedule 8812
Line 5 Worksheet
----------------
    TAXSIM35   
----------------
(L1)       0  [no children under 6 years old]
(L2)   12000  [=4*3000]
(L3)   12000  [sum of (L1) and (L2)]
(L4)    8000  [=4*2000]
(L5)    4000  [= (L3) minus (L4)]
(L6)    4375  [HoH filing status]
(L7)    4000  [= minimum of (L5) and (L6)]
(L8)  112500  [HoH filing status]
(L9)    5400  [= Sch8812(L3)=117900 minus 112500 with no rounding]
(L10     270  [= 5% of (L9)]
(L11)    270  [= minimum of (L7) and (L10)]
(L12)  11730  [= (L3) minus (L11)]
----------------
```
