### ISSUE TITLE
Double subtraction of 2021 US CDCC?

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1100]
For one year only in 2021, the CDCC was fully refundable.  The following test case suggests the possibility that OpenFisca-US 0.97.0 version is subtracting out the CDCC amount **twice** in that year.   Is that what is causing the difference in US income tax liability for the test case below?  The two models agree on all the intermediate amounts but OpenFisca-US ends up with an income tax amount that is less than TAXSIM35 by the amount of the CDCC.

Here is the test case followed by its test results and a discussion:

```
# OpenFisca-US test file derived from r21.its.csv and r21.ota.csv files

- name: Tax unit with taxsimid 52 from r21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 55
        employment_income: 125000
        taxable_interest_income: 5000
        short_term_capital_gains: 2000
        long_term_capital_gains: 6000
        real_estate_taxes: 6000
        interest_expense: 16000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 55
        employment_income: 35000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 5000
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3]
        state_code: TX
  output:
    taxsim_tfica: 12240.00
    income_tax: 20315.00
```

Test results:
```
  Test 'Tax unit with taxsimid 52 from r21.its.csv':
    income_tax@2021: [19015.] differs from 20315.0 
      with an absolute margin [1300.] > 0.01
```

The trace results include the following:

```
taxable_income<2021> >> [147900.]
alternative_minimum_tax<2021> >> [0.]
income_tax_before_credits<2021> >> [23615.]
cdcc<2021> >> [1300.]
non_refundable_ctc<2021> >> [0.]
income_tax_non_refundable_credits<2021> >> [1300.]
income_tax_capped_non_refundable_credits<2021> >> [1300.]
income_tax_before_refundable_credits<2021> >> [22315.]
refundable_ctc<2021> >> [2000.]
eitc<2021> >> [0.]
income_tax<2021> >> [19015.]
```

The two models agree on the tax before credits ($23,615), on the CDCC amount ($1300), and on the CTC amount ($2000).
```
TAXSIM35:      23615 - 1300 - 2000 = 20315
OpenFisca-US:  23615 - 1300 - 2000 - 1300 = 19015
```
