### ISSUE TITLE
US net Investment income tax (NIIT) is never calculated

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1111]
There is an `niit` variable with a formula, but it doesn't seem to be included in the US income tax before credits variable.  The missing NIIT shows up in the following test case:
```
- name: Tax unit with taxsimid 74740 from r21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 24
        employment_income: 160000
        taxable_interest_income: 10000
        short_term_capital_gains: 10000
        long_term_capital_gains: 10000
        social_security: 19000
        real_estate_taxes: 21000
        interest_expense: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 29
        employment_income: 102000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        tax_unit_childcare_expenses: 9000
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: TX
  output:
    taxsim_tfica: 19084.60
    income_tax: 50614.00
```

The test results for this case are as follows:
```
  Test 'Tax unit with taxsimid 74740 from r21.its.csv':
    income_tax@2021: [49474.] differs from 50614.0
      with an absolute margin [1140.] > 0.01
```

The trace output does not include the `niit` variable, which indicates the problem.  The $30,000 in investment income should be taxed at 3.8% for a tax liability of $1140.  The two models agree on all other intermediate variables: AGI, taxable income, and credits.  The tax difference is attributable to the fact that OpenFisca-US 0.98.1 version does not integrate `niit` into the federal tax system.
