### ISSUE TITLE
Problem with US income taxation of long-term capital gains

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1195]
The 2021 income tax amounts from OpenFisca-US and TAXSIM35 differ substantially in many cases where there are long-term capital gains.  While it is difficult for me to understand what part of the code is handling the favorable tax treatment of qualified dividends and long-term capital gains, the trace information suggests that perhaps long-term capital gains are receiving their special tax treatment and then they are being inadvertently taxed again as regular income.  The TAXSIM35 results for these cases are the same as generated by the US Tax Analyzer model.

Here is a YAML test file and its results.
```
# OpenFisca-US test file derived from t21.its.csv and t21.ota.csv files
- name: Tax unit with taxsimid 95009 from t21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 49000
        taxable_interest_income: 9000
        long_term_capital_gains: 10000
        social_security: 21000
        real_estate_taxes: 17000
        interest_expense: 25000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        tax_unit_childcare_expenses: 9000
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 3748.50
    income_tax: -5182.00
```
Using the above file to run the test gives these results:
```
(openfisca-us) US% openfisca-us test t21-id95009.test.yaml 
---[SNIP]---            
/Users/mrh/work/OpenFisca-US/US/t21-id95009.test.yaml:
  Test 'Tax unit with taxsimid 95009 from t21.its.csv':
    income_tax@2021: [-3982.] differs from -5182.0 
      with an absolute margin [1200.] > 0.01
---[SNIP]--- 
```

Using this YAML test file, we get a $1200 tax difference.  Note that according to TAXSIM35, this test case has a marginal tax rate (on regular income) of 12%.  And 12% of $10,000 in LTCG happens to be equal to the $1200 income tax difference.   Is there a different explanation for why OpenFisca-US gets an income tax amount that is $1200 greater than the other two models?
