### ISSUE TITLE
Incorrect EITC calculation caused by ill-defined dividend_income variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1196]
US EITC eligibility is incorrectly calculated in the presence of `qualified_dividend_income` and/or `non_qualified_dividend_income`.  This bug is caused by the existence of the `dividend_income` variable, which (as far as I can see) should be completely eliminated from the OpenFisca-US model.  For the confusion cause by the existence of this ill-defined variable, see issue #1187.

And it not just confusion for a reader of the source code, but its existence is leading to tax calculation errors as shown in the simple test case presented below.  My recommendation on how to fix the bug reported below would be to change all the instances of `dividend_income` to `ordinary_dividend_income` (which is correctly defined as the sum of `qualified_dividend_income` and `non_qualified_dividend_income`), and then remove the `dividend_income` variable for the model.

Here is the YAML test file for this simple case followed by the test results, which show a $765 US tax difference because OpenFisca-US thinks the case is eligible for the EITC (which neither TAXSIM35 nor US Tax Analyzer think is true).

First, the test file:
```
# OpenFisca-US test file derived from u21.its.csv and u21.ota.csv files
- name: Tax unit with taxsimid 97950 from u21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 5000
        non_qualified_dividend_income: 11000
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 382.50
    income_tax: -1055.00
```

Now the test results in which OpenFisca-US thinks this case is eligible for an EITC of $765 despite having investment income of $11,000:
```
(openfisca-us) US% ../extract_case.sh u21 97950 TAOUT
---[SNIP]---
  Test 'Tax unit with taxsimid 97950 from u21.its.csv':
    income_tax@2021: [-1820.] differs from -1055.0
      with an absolute margin [765.] > 0.01
---[SNIP]---
Trace output is in file: u21-id97950.test.trace

(openfisca-us) US% grep eitc u21-id97950.test.trace | head -3
                                eitc<2021> >> [765.]
                                    eitc_eligible<2021> >> [ True]
                                    eitc_maximum<2021> >> [1502.]
```
