### ISSUE TITLE
US tax difference for case with long-term capital gains

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1222]
The case described below has been generated using the **r21** **US** sample and adding random long-term capital gains amounts. The **r21** sample (without long-term capital gains amounts) produces no differences between OpenFisca-US and TAXSIM35 (and the US Tax Analyzer).

But in the case below, when adding $19,000 in long-term capital gains, we get an US income tax difference of $2055.  First the YAML test file containing the case, then the test results, and finally a discussion of the income tax difference.

Here is the test case:
```
# OpenFisca-US test file derived from i21.its.csv and i21.ota.csv files
- name: Tax unit with taxsimid 91330 from i21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 62
        employment_income: 63000
        taxable_interest_income: 6000
        long_term_capital_gains: 19000
        social_security: 9000
        real_estate_taxes: 12000
        interest_expense: 30000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: TX
  output:
    taxsim_tfica: 4819.50
    income_tax: -10253.50
```

Here are the results for the above test:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/OpenFisca-US/US/i21-id91330.test.yaml:
  Test 'Tax unit with taxsimid 91330 from i21.its.csv':
    income_tax@2021: [-8198.5] differs from -10253.5
      with an absolute margin [2055.] > 0.01
========================= short test summary info ============================
FAILED i21-id91330.test.yaml::
============================ 1 failed in 1.05s ===============================
Trace output is in file: i21-id91330.test.trace
```

Notice that this test case has $19,000 in long-term capital gains, no short-term capital gains, and no dividend income of any kind.

All three models agree on AGI ($95,650) and taxable income ($55,650), but disagree on tax before credits with OpenFisca-US getting 6401.50 and the other two models getting 4346.50 (which is a difference of 2055).  The models also disagree on the US income tax liability with OpenFisca-US getting -8198.50 and the other two models getting -10253.50, which is also a difference of $2055 because the models agree on the tax credits for this test case.

TAXSIM35 splits the taxable income into two amounts and taxes them in different ways.  The first amount equals taxable income minus long-term capital gains, which is 36,650.  This first amount is taxed as regular income producing a liability of 4114.  And the remaining second amount of 19,000 generates a liability of 232.50.  Combining these two liability amounts yields 4346.50, which after subtracting the refundable credits of 14,600, produces the TAXSIM35 total US income tax liability of -10,253.50.

On the other hand, the OpenFisca-US trace output contains this entry:
```
capital_gains_tax<2021> >> [2287.5]
```
I don't understand how OpenFisca-US gets, a long-term capital gains tax of 2287.50 for this test case.   @nikhilwoodruff, can you explain exactly how OpenFisca-US gets this 2287.50 capital gains tax?  Getting an answer to this question is important because the 2055 tax difference is equal to the difference in the capital gain tax (2287.50 - 232.50 = 2055.00).  How is OpenFisca-US calculating the portion of long-term capital gains that are subject to a zero tax rate?
