### ISSUE TITLE
QBID testing

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1237]
Let's begin the validation testing of the US qualified business income deduction (QBID) calculations in Texas, where the absence of a state income tax means the issue #1235 is not relevant.

Instead of using a large sample of randomly-generated test cases that have been run through TAXSIM35 and US Tax Analyzer, we begin using the six tax units described in a [2018 Tax Policy Center (TPC) publication](https://www.taxpolicycenter.org/publications/navigating-new-pass-through-provisions-technical-explanation/full).  The first three tax units in the TPC publication cannot be specified in the 0.125.0 version of OpenFisca-US because there is no variable called `business_is_sstb` that can be specified independently of the `business_is_qualified` variable.  For a more complete discussion of this problem, read issue #903.

However, the second three tax units in the TPC publication can be specified in the following YAML test file:
```
# OpenFisca-US test file derived from TPC publication test cases
#
# Test OpenFisca-US QBID calculations using the six tax units specified in
# Table 1 of this TPC publication: "Navigating the New Pass-Through Provisions:
# A Technical Explanation" by William G. Gale and Aaron Krupkin
# (January 31, 2018), which is available at this URL:
# https://www.taxpolicycenter.org/publications/navigating-new-pass-through-provisions-technical-explanation/full
#
# In constructing the TPC publication tax units, assume that the taxpayer
# has business income in the form of S-corporation income and no earnings,
# and that the spouse has no business income and only wage earnings.
# Assume that the taxpayer's share of the S corporation W2 wages is always
# $20,000 and that the taxpayer's share of the S corporation property is
# always $90,000.

# TPC publication tax units 1-3 cannot be specified using the 0.124.1 code
# because there is no business_is_sstb variable that can be set independently
# of the business_is_qualified variable.

- name: TPC publication tax unit 4
  absolute_error_margin: 0.01
  period: 2018
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        partnership_s_corp_income: 75000
        business_is_qualified: true
        w2_wages_from_qualified_business: 20000
        unadjusted_basis_qualified_property: 90000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 99000
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    qualified_business_income_deduction: 15000

- name: TPC publication tax unit 5
  absolute_error_margin: 0.01
  period: 2018
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        partnership_s_corp_income: 75000
        business_is_qualified: true
        w2_wages_from_qualified_business: 20000
        unadjusted_basis_qualified_property: 90000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 349000
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    qualified_business_income_deduction: 10750

- name: TPC publication tax unit 6
  absolute_error_margin: 0.01
  period: 2018
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        partnership_s_corp_income: 75000
        business_is_qualified: true
        w2_wages_from_qualified_business: 20000
        unadjusted_basis_qualified_property: 90000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 524000
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    qualified_business_income_deduction: 10000
```

The test results show one pass and two fails:
```
============================= test session starts ==============================
platform darwin -- Python 3.7.13, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /Users/mrh/work/OpenFisca-US/US
plugins: dependency-0.5.1
collected 3 items                                                              

qbid-tpc.test.yaml .FF

================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/OpenFisca-US/US/qbid-tpc.test.yaml:
  Test 'TPC publication tax unit 5':
    qualified_business_income_deduction@2018: [14225.] differs from 10750.0
      with an absolute margin [3475.] > 0.01
_______________________________ test session _________________________________
/Users/mrh/work/OpenFisca-US/US/qbid-tpc.test.yaml:
  Test 'TPC publication tax unit 6':
    qualified_business_income_deduction@2018: [7250.] differs from 10000.0
      with an absolute margin [2750.] > 0.01
======================= 2 failed, 1 passed in 0.51s ==========================
```

The TPC publication provides a nice walk-through of the QBID calculations for these cases, so reading that short publication should point to the problems OpenFisca-US is having.  By the way, the six TPC publication tax units have been part of the US Tax Analyzer unit test suite for years.
