### ISSUE TITLE
Flaw in 2021 US CTC calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1270]
There is at least one flaw in the 2021 formulas used to compute the US CTC.  The flaw causes the value of the credit in some cases to be negative, which is a nonsensical value for any tax credit.  This flaw manifests itself only in 2021, the only year in which the CTC is fully refundable.

Here is the YAML file for a test case that illustrates this problem.  After showing the YAML test file, I show the test results: a $1000 over-estimate of federal income tax liability caused by the calculation of a -$1000 amount for the `non_refundable_ctc` variable, in a year during which there is no such thing as a non-refundable child tax credit.  And after showing the test results, I venture a **guess** about which formula contains the flaw.

Here is the test case:
```
# OpenFisca-US test file derived from m21.ita.csv and m21.ota.csv files
- name: Tax unit with recid 95001 from m21.ita.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 64
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 175000
        taxable_interest_income: 100000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 11391.10
    income_tax: 65615.00
```

Here are the results for the above test case:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/m21-id95001.test.yaml:
  Test 'Tax unit with recid 95001 from m21.ita.csv':
    income_tax@2021: [66615.] differs from 65615.0 
    with an absolute margin [1000.] > 0.01
========================= short test summary info ============================
FAILED m21-id95001.test.yaml::
============================ 1 failed in 1.20s ===============================
```

The CTC-related trace output from the above test includes these lines:
```
  ctc_maximum<2021> >> [3000.]
  ctc_reduction<2021> >> [4000.]
  ctc<2021> >> [-1000.]
  non_refundable_ctc<2021> >> [-1000.]
  refundable_ctc<2021> >> [0.]
```

The OpenFisca-US `income_tax` is $1000 larger than the amount generated by US Tax Analyzer because the -1000 `non_refundable_ctc` is subtracted from the tax before credits.

Although there may be other flaws in the 2021 CTC formulas, there is one formula that looks incomplete.  Here is the `ctc` formula:
```
class ctc(Variable):
    value_type = float
    entity = TaxUnit
    label = "Child Tax Credit"
    unit = USD
    documentation = "Total value of the non-refundable and refundable portions of the Child Tax Credit."
    definition_period = YEAR
    reference = "https://www.law.cornell.edu/uscode/text/26/24#a"

    def formula(tax_unit, period, parameters):
        maximum_amount = tax_unit("ctc_maximum", period)
        reduction = tax_unit("ctc_reduction", period)
        return maximum_amount - reduction
```

Notice that this formula does not guard against negative `ctc` amounts.  While there may be other flaws in the CTC-related formulas for 2021, this is definitely a flaw that needs fixing.
