### ISSUE TITLE
Education credit differences with USI-Tax-Analyzer

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1298]
After adding qualified tuition expenses as an input variable to the validation tests summarized in issue #1280, it appears as if there is an education credit problem in the 0.129.2 version of OpenFisca-US.  This issue presents a simple 2021 tax unit for which OpenFisca-US computes the correct ($800) Lifetime Learning Credit (LLC), but ignores the fact that this tax unit has the option of applying its tuition towards an American Opportunity Credit (AOC), which would be $2500.   This $1700 difference accounts for the income tax difference between the two models.

Note that it is not possible to simulate this tax unit using TAXSIM35 because that model does not simulate education credits.   Instead, the [2021 Form 1040 Schedule 8863 form](https://www.irs.gov/pub/irs-pdf/f8863.pdf) has been filled out by hand for this tax unit, confirming both the $800 LLC amount and the $2500 AOC amount.  Schedule 8863 makes it clear that there is a choice (see screenshot below).  Is OpenFisca-US not modeling this taxpayer choice?

<img width="1118" alt="Screen Shot 2022-08-30 at 12 03 12 PM" src="https://user-images.githubusercontent.com/12170745/187485916-cc19bca9-e101-450a-9f05-e09aa16360ff.png">

Here is the YAML test case and below it are the test results for this case.
```
# OpenFisca-US test file derived from m21.ita.csv and m21.ota.csv files
- name: Tax unit with recid 99980 from m21.ita.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 45
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 79000
        qualified_tuition_expenses: 4000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 20
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3]
        state_code: TX
  output:
    taxsim_tfica: 6043.50
    income_tax: -2660.00
```

Here are the test results for the above case:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/m21-id99980.test.yaml:
  Test 'Tax unit with recid 99980 from m21.ita.csv':
    income_tax@2021: [-960.] differs from -2660.0
      with an absolute margin [1700.] > 0.01
========================= short test summary info ============================
FAILED m21-id99980.test.yaml::
============================ 1 failed in 1.16s ===============================
```

Here is some of the OpenFisca-US test trace output:
```
lifetime_learning_credit<2021> >> [800.]
american_opportunity_credit<2021> >> [0.]
refundable_american_opportunity_credit<2021> >> [0.]
```

And here is part of the USI-Tax-Analyzer dump output:
```
c00100 79000.0
c04800 60200.0
c05800 7540.0
etc_llc_option 0      <--- elects to apply tuition to AOC rather than LLC
c07230 1500.0         <--- nonrefundable AOC amount
c10960 1000.0         <--- refundable AOC amount
c11070 3000.0
itax -2660.0
odc 500.0
rrc 4200.0
taxbc 7540.0
```
