### ISSUE TITLE
Incorrect calculation of MA taxable income

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1354]
The formula for the [`ma_part_b_taxable_income_deductions` variable](https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/variables/gov/states/ma/tax/income/taxable_income/ma_part_b_taxable_income_deductions.py) is incorrect in OpenFisca-US 0.147.3 version because it includes dividends (not just interest) in the calculation of the Massachusetts bank interest exemption.  I tried to look at the legislative reference provided for this variable and for the corresponding [`ma_interest_exemption` parameter](https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/gov/states/ma/tax/income/exemptions/interest.yaml), but in both cases I get this:

<img width="1326" alt="Screen Shot 2022-09-09 at 11 31 59 AM" src="https://user-images.githubusercontent.com/12170745/189389797-4b0df99e-749f-4fca-946e-08ab57f77993.png">

The following Massachusetts government document about the MA bank interest exemption says nothing about qualified dividends being eligible for the exemption.

<img width="628" alt="Screen Shot 2022-09-09 at 11 30 59 AM" src="https://user-images.githubusercontent.com/12170745/189390365-f0d029e4-6e27-441c-b6cb-937258c728c4.png">

Here is a test case that illustrates the problem: OpenFisca-US generates a MA taxable income that is $200 less than generated by either TAXSIM35 or MAI-Tax-Analyzer (which are in agreement on taxable income):
```
# OpenFisca-US test file derived from o21.ita.csv and o21.ota.csv files
- name: Tax unit with recid 99920 from o21.ita.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 70
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 17000
        qualified_dividend_income: 59000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 68
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 2000
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 20
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 20
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: MA
  output:
    ma_income_tax: 2487.33
```
