### ISSUE TITLE
Add SPM unit `nb_persons` variable

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#324]
Our unit tests are currently cluttered with `persons` definitions that include some baseline characteristic to create an SPM unit from (example below). A SPM-unit-level variable with the formula of `spm_unit.nb_persons()` would enable us to simplify these tests (which will also be useful for demonstration and potentially for end users).

@nikhilwoodruff or is there another way to define SPM units from persons as concisely as this without adding a variable?

Example:
https://github.com/PolicyEngine/openfisca-us/blob/1cad643d55286b4bee6ff6047c0cbc8b5714a52d/openfisca_us/tests/policy/baseline/usda/school_meals/school_meals.yaml#L1-L18

Alternative:
```yaml
- name: No income, one parent, one child, contiguous_US 
   period: 2022 
   absolute_error_margin: 0.01 
   input: 
     spm_units: 
       spm_unit: 
         nb_persons: 2
         spm_unit_school_meal_fpg_ratio: 0 
     households: 
       household: 
         state_group: CONTIGUOUS_US 
   output: 
     school_meal_subsidy: 180 * (3.66 + 1.97)
```
