### ISSUE TITLE
Incorrect 2018 ACTC calculation in some cases

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#824]
OpenFisca-US generates too large an amount for the refundable ACTC in some cases in 2018.

Beginning in 2018 the TCJA introduced a non-refundable other dependent credit (ODC).  This credit is calculated along with the non-refundable portion of the child tax credit (CTC) in the <em>Child Tax Credit and Credit for Other Dependents Worksheet</em> in the [2019 Form 1040 instructions](https://www.irs.gov/pub/irs-prior/i1040gi--2019.pdf) starting on page 35.  The refundable portion of the CTC, which is called the additional child tax credit (ACTC) is calculated on [2019 Schedule 8812](https://www.irs.gov/pub/irs-prior/f1040s8--2019.pdf).

The Schedule 8812 document makes it clear that no portion of the ODC is eligible for inclusion in the refundable ACTC.  But the 0.70.3 version of OpenFisca-US does include ODC in the ACTC.  Here is a tax unit that illustrates the problem:

```
(openfisca-us) OpenFisca-US% cat f19-id663.test.yaml 
# OpenFisca-US test file derived from the f19.its.csv and f19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 663 from f19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 73
        employment_income: 2000
        pension_income: 11000
        social_security: 3000
        unemployment_compensation: 2000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 69
        employment_income: 22000
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 12
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 17
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 17
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0
        tax_unit_childcare_expenses: 8000
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: TX
  output:
    taxsim_tfica: 1836.00
    #tax_unit_taxable_unemployment_compensation: 2000.00
    #tax_unit_taxable_social_security: 1500.00
    #adjusted_gross_income: 38500.00
    #taxable_income: 11500.00
    #cdcc: 465.00
    #non_refundable_ctc: 685.00
    #refundable_ctc: 1400.00
    #eitc: 3675.99
    income_tax: -5075.99

(openfisca-us) OpenFisca-US% openfisca-us test -v f19-id663.test.yaml > f19-id663.test.trace

(openfisca-us) OpenFisca-US% tail -5 f19-id663.test.trace | grep -v =
  Test 'Tax unit with taxsimid 663 from f19.its.csv':
    income_tax@2019: [-5925.992] differs from -5075.990234375 
      with an absolute margin [850.00195] > 0.01
FAILED f19-id663.test.yaml::

(openfisca-us) OpenFisca-US% ./show_output.sh f19-id663
>>> Trace output from OpenFisca-US:
taxsim_tfica<2019> >> [1836.]
tax_unit_taxable_unemployment_compensation<2019> >> [2000.]
tax_unit_taxable_social_security<2019> >> [1500.]
adjusted_gross_income<2019> >> [38500.]
taxable_income<2019> >> [11500.]
income_tax_before_credits<2019> >> [1150.]
elderly_disabled_credit<2019> >> [0.]
cdcc<2019> >> [400.]
non_refundable_ctc<2019> >> [750.]
income_tax_non_refundable_credits<2019> >> [1150.]
income_tax_capped_non_refundable_credits<2019> >> [1150.]
income_tax_before_refundable_credits<2019> >> [0.]
refundable_ctc<2019> >> [2250.]
eitc<2019> >> [3675.992]
income_tax<2019> >> [-5925.992]
>>> Expected output from TAXSIM35:
    taxsim_tfica: 1836.00
    #tax_unit_taxable_unemployment_compensation: 2000.00
    #tax_unit_taxable_social_security: 1500.00
    #adjusted_gross_income: 38500.00
    #taxable_income: 11500.00
    #cdcc: 465.00
    #non_refundable_ctc: 685.00
    #refundable_ctc: 1400.00
    #eitc: 3675.99
    income_tax: -5075.99
```

TAXSIM35 computes the ACTC amount as $1400, which is the maximum amount for the ACTC when there is one qualified dependent under age 17.

OpenFisca-US incorrectly includes $850 in "unused ODC credits" in the ACTC amount, which exceeds the maximum ACTC amount of $1400 for a case with only one qualified dependent under age 17.

**Comment by martinholmer** [comment]
The initial comment in Issue #824 included a test case in which the ACTC (`refundable_ctc`) was incorrect in the presence of children who are age 17+.  This comment includes another test case in which the ACTC amount is incorrect even though all dependents are less than age 17 (that is, there is no ODC involved).   When fixing the code in response to issue #824, both these test cases should pass.

Here is the second test case:
```
(openfisca-us) OpenFisca-US% cat f19-id744.test.yaml 
# OpenFisca-US test file derived from the f19.its.csv and f19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 744 from f19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 72
        employment_income: 16000
        pension_income: 2000
        social_security: 33000
        unemployment_compensation: 8000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 12
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
        tax_unit_childcare_expenses: 3000
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 1224.00
    #tax_unit_taxable_unemployment_compensation: 8000.00
    #tax_unit_taxable_social_security: 11725.00
    #adjusted_gross_income: 37725.00
    #taxable_income: 17725.00
    #cdcc: 709.12
    #non_refundable_ctc: 1140.88
    #refundable_ctc: 859.12
    #eitc: 538.54
    income_tax: -1397.66

(openfisca-us) OpenFisca-US% openfisca test f19-id744.test.yaml 
---[SNIP]---
  Test 'Tax unit with taxsimid 744 from f19.its.csv':
    income_tax@2019: [-1288.5391] differs from -1397.6600341796875 
    with an absolute margin [109.12097] > 0.01
---[SNIP]---
======================== 1 failed in 0.12s =========================
```
