### ISSUE TITLE
CDCC is a non-refundable credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#842]
After upgrading to the 0.68.1 version, I still get some test failures caused by the current `cdcc` formula lacking any non-refundable logic.  By definition,  the amount of a non-refundable credit can never be more than the pre-credit income tax liability.

To illustrate this problem, here is a test case in which a $1750 CDCC is assigned to a parent with zero taxable income:
```
(openfisca-us) OpenFisca-US% cat f19-id217.test.yaml 
# OpenFisca-US test file derived from the f19.its.csv and f19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 217 from f19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 66
        employment_income: 6000
        unemployment_compensation: 4000
        social_security: 21000
        pension_income: 2000
        has_marketplace_health_coverage: false
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 12
        has_marketplace_health_coverage: false
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 12
        has_marketplace_health_coverage: false
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        has_marketplace_health_coverage: false
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 20
        has_marketplace_health_coverage: false
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 5000
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: TX
  output:
    tax_unit_taxable_unemployment_compensation: 4000.00
    tax_unit_taxable_social_security: 0.00
    adjusted_gross_income: 12000.00
    taxable_income: 0.00
    cdcc: 0.00
    non_refundable_ctc: 0.00
    refundable_ctc: 525.00
    eitc: 2700.00
    income_tax: -3225.00

(openfisca-us) OpenFisca-US% openfisca-us test f19-id217.test.yaml 
---[snip]---
  Test 'Tax unit with taxsimid 217 from f19.its.csv':
    cdcc@2019: [1750.] differs from 0.0 with an absolute margin [1750.] > 0.01
---[snip]---
====================== 1 failed in 0.06s ========================
```

@MaxGhenis @nikhilwoodruff
