### ISSUE TITLE
Formula for refundable_ctc variable missing a key condition

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#848]
The `refundable_ctc` formula contains some code that is headed with this comment:
```
# Compute "Social Security taxes" as defined in the US Code for the ACTC.
# This includes OASDI and Medicare payroll taxes, as well as half
# of self-employment taxes.
```
The current formula does these computations for **all** tax_units when actually they should be done only for tax_units that have three or more qualifying children who are under seventeen.

Perhaps the legal language in the law makes it difficult to understand that, but the one-page [Form 1040 Schedule 8812](https://www.irs.gov/pub/irs-prior/f1040s8--2019.pdf) ("Additional Child Tax Credit") makes it quite clear who is expected to fill out Part II and who is not.

This consequences of this problem is illustrated in the following test case:
```
(openfisca-us) OpenFisca-US% cat f19-id26.test.yaml
# OpenFisca-US test file derived from the f19.its.csv and f19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 26 from f19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 70
        employment_income: 2000
        unemployment_compensation: 1000
        social_security: 36000
        pension_income: 27000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3]
        state_code: TX
  output:
    tax_unit_taxable_unemployment_compensation: 1000.00
    tax_unit_taxable_social_security: 16400.00
    adjusted_gross_income: 46400.00
    taxable_income: 26400.00
    refundable_ctc: 0.00
    eitc: 63.88
    income_tax: -63.88

(openfisca-us) OpenFisca-US% openfisca-us test f19-id26.test.yaml
---[snip]---
  Test 'Tax unit with taxsimid 26 from f19.its.csv':
    refundable_ctc@2019: [153.] differs from 0.0 with an absolute margin [153.] > 0.01
---[snip]---
========================= 1 failed in 0.06s ==========================
```

This tax_unit has only two children, so does not need to fill out Part II on Schedule 8812, and hence, TAXSIM35 computes a zero ACTC amount for this case.  But OpenFisca-US computes an ACTC amount of $153, which is the employee portion of the OASDHI payroll tax.  This does not seem correct.

@MaxGhenis @nikhilwoodruff
