### ISSUE TITLE
Add missing step in section_22_income variable formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#857]
The `section_22_income` variable is used to compute the `elderly_disabled_credit` variable in the `variables/gov/irs/credits/elderly_and_disabled/` directory.  The formula for `section_22_income` seems correct except for one missing step: the non-taxable portion of social security benefits is not subtracted out along with the non-taxable portion of pension benefits.  On the [Schedule R form](https://www.irs.gov/pub/irs-prior/f1040sr--2019.pdf), this corresponds to line 13a always being zero (which is incorrect for anyone with social security benefits).  This means that some tax_units have `section_22_income` that is too large, and hence, have an `elderly_disabled_credit` that is too large.

This problem is illustrated in the following test case (in which `income_tax` should be $15, but the current code computes an incorrect credit of $112.50 that reduces the $15 to zero):

```
(openfisca-us) OpenFisca-US% cat g19-id999.test.yaml
# OpenFisca-US test file derived from the g19.its.csv and g19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 999 from g19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 67
        short_term_capital_gains: 6000
        rental_income: 2000
        pension_income: 1000
        social_security: 10000
        unemployment_compensation: 5000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    tax_unit_taxable_unemployment_compensation: 5000.00
    tax_unit_taxable_social_security: 0.00
    adjusted_gross_income: 14000.00
    taxable_income: 150.00
    refundable_ctc: 0.00
    eitc: 0.00
    income_tax: 15.00

(openfisca-us) OpenFisca-US% openfisca-us test g19-id999.test.yaml
---[SNIP]---
  Test 'Tax unit with taxsimid 999 from g19.its.csv':
    income_tax@2019: [0.] differs from 15.0 with an absolute margin [15.] > 0.01
======================== 1 failed in 0.12s =========================
```
