### ISSUE TITLE
Question about the taxable_ss_magi formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#860]
Seems as if the `taxable_ss_magi` formula is not quite right when there are capital losses.  In the test case below, there are $18,000 in (short-term plus long-term) capital losses, which implies that the `loss_ald` is $3000.  But the current version of the `taxable_ss_magi` formula adds to positive income amounts the -18000 and then subtracts the 3000, getting a MAGI amount of $35,000.  Does it seem correct to do a "double" subtraction of the `loss_ald` amount?  

Both TAXSIM35 and Tax-Calculator are subtracting just the `loss_ald` amount, in this case, which leads those models to get a MAGI of $53,000.  I'm not sure this is correct either.

When you look back at the legislative language, what does it say about the handling of capital losses when computing the MAGI used to determine the taxable portion of social security benefits?

Here is a test case that illustrates this difference between the models:

```
(openfisca-us) OpenFisca-US% cat g19-id3.test.yaml
# OpenFisca-US test file derived from the g19.its.csv and g19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 3 from g19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 27
        taxable_interest_income: 14000
        short_term_capital_gains: -10000
        long_term_capital_gains: -8000
        pension_income: 38000
        social_security: 1000
        unemployment_compensation: 4000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 26
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    tax_unit_taxable_unemployment_compensation: 4000.00
    tax_unit_taxable_social_security: 850.00
    adjusted_gross_income: 53850.00
    taxable_income: 29450.00
    refundable_ctc: 0.00
    eitc: 0.00
    income_tax: 3146.00

(openfisca-us) OpenFisca-US% openfisca test g19-id3.test.yaml
---[SNIP]---
  Test 'Tax unit with taxsimid 3 from g19.its.csv':
    tax_unit_taxable_social_security@2019: [500.] differs from 850.0 
    with an absolute margin [350.] > 0.01
```
