### ISSUE TITLE
Problems with elderly_disabled_credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#868]
In the 0.70.3 code, the calculation of the `elderly_disabled_credit` is incorrect.  The problem is rooted in the `section_22_income` formula, which in the test case below returns zero when it should return $1250.  After showing the test case and test results, the Schedule R form for the test case is filed out to show the correct logic.

Here is the test that fails:

```
(openfisca-us) OpenFisca-US% cat g19-id7035.test.yaml   
# OpenFisca-US test file derived from the g19.its.csv and g19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 7035 from g19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 67
        taxable_interest_income: 8000
        short_term_capital_gains: -6000
        long_term_capital_gains: 2000
        pension_income: 9000
        unemployment_compensation: 1000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    #tax_unit_taxable_unemployment_compensation: 1000.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 15000.00
    #taxable_income: 1150.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    income_tax: 0.00

(openfisca-us) OpenFisca-US% openfisca-us test g19-id7035.test.yaml
---[SNIP]---
  Test 'Tax unit with taxsimid 7035 from g19.its.csv':
    income_tax@2019: [115.] differs from 0.0 with an absolute margin [115.] > 0.01
---[SNIP]---
======================== 1 failed in 0.14s =========================
```

Using the 2019 IRS Form 1040 Schedule R [form](https://www.irs.gov/pub/irs-prior/f1040sr--2019.pdf) and [instructions](https://www.irs.gov/pub/irs-prior/i1040sr--2019.pdf), we have for the above test case:
```
Box 1:   check
Line 10:  5000
Line 12:  5000
Line 13a:    0
Line 13b:    0
Line 13c:    0
Line 14: 15000   <--- AGI
Line 15:  7500
Line 16:  7500
Line 17:  3750
Line 18:  3750
Line 19:  1250   <--- "section_22_income"
Line 20:   187.50
Line 21:   115.00  <--- see Schedule R Credit Limit Worksheet calcs below
Line 22:   115.00

Credit Limit Worksheet calculations:
Line 1:  income tax liability before credits:   115.00
Line 2:  sum of cdcc and foreign tax credit:      0.00
Line 3:  max(0, line1 - line2):                 115.00
```
