### ISSUE TITLE
Incorrect standard-vs-itemized US income tax deduction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#886]
The standard-vs-itemized US income tax deduction logic is incorrect in the 0.73.0 code.  OpenFisca-US correctly calculates the deduction amount if itemizing and the deduction amount if not itemizing, but then fails to make the choice the minimizes the tax unit's US income tax liability.   

Below is a test case that illustrates this problem:

```
# OpenFisca-US test file derived from h19.its.csv and h19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/06/22) With TCJA

- name: Tax unit with taxsimid 2 from h19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 33
        taxable_interest_income: 1000
        long_term_capital_gains: -8000
        pension_income: 31000
        social_security: 1000
        unemployment_compensation: 9000
        real_estate_taxes: 22000
        interest_expense: 36000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    #tax_unit_taxable_unemployment_compensation: 9000.00
    #tax_unit_taxable_social_security: 850.00
    #adjusted_gross_income: 38850.00
    #taxable_income: 0.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    income_tax: 0.00
```

Here are the test results:

```
  Test 'Tax unit with taxsimid 2 from h19.its.csv':
    income_tax@2019: [3004.] differs from 0.0 with an absolute margin [3004.] > 0.01
```

So, the tax unit pays over $3000 more in taxes by mistakenly taking the standard deduction as seen in the following trace output:

```
>>> Trace output from OpenFisca-US:
taxsim_tfica<2019> >> [0.]
tax_unit_taxable_unemployment_compensation<2019> >> [9000.]
tax_unit_taxable_social_security<2019> >> [850.]
adjusted_gross_income<2019> >> [38850.]
tax_unit_itemizes<2019> >> [False]
tax_liability_if_itemizing<2019> >> [0.]
tax_liability_if_not_itemizing<2019> >> [0.]
taxable_income_deductions_if_itemizing<2019> >> [46000.]
taxable_income_deductions_if_not_itemizing<2019> >> [12200.]
taxable_income<2019> >> [26650.]
income_tax_before_credits<2019> >> [3004.]
elderly_disabled_credit<2019> >> [0.]
cdcc<2019> >> [0.]
non_refundable_ctc<2019> >> [0.]
income_tax_non_refundable_credits<2019> >> [0.]
income_tax_capped_non_refundable_credits<2019> >> [0.]
income_tax_before_refundable_credits<2019> >> [3004.]
refundable_ctc<2019> >> [0.]
eitc<2019> >> [0.]
income_tax<2019> >> [3004.]
```

This test case is for 2019 but the problem is with the logic so this kind of problem would arise in every year.
