### ISSUE TITLE
Federal taxation of long-term capital gains differs from TAXSIM35

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#896]
Using the 0.73.1 version of OpenFiscal-US, the following test case indicates a difference with TAXSIM35 related to handling the federal taxation of long-term capital gains (and qualified dividends).   First the test case is presented, then the tax liability difference, and finally some discussion of the tax liability difference.  (The test case is for 2019 but the root of the difference seems to be in the logic, so this kind of difference would arise in any year.)

Here is the tax case:
```
# OpenFisca-US test file derived from h19.its.csv and h19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/06/22) With TCJA

- name: Tax unit with taxsimid 184 from h19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 27
        taxable_interest_income: 14000
        short_term_capital_gains: 10000
        long_term_capital_gains: 10000
        pension_income: 51000
        social_security: 53000
        unemployment_compensation: 6000
        real_estate_taxes: 20000
        interest_expense: 39000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    #tax_unit_taxable_unemployment_compensation: 6000.00
    #tax_unit_taxable_social_security: 45050.00
    #adjusted_gross_income: 136050.00
    #taxable_income: 87050.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    income_tax: 14309.50
```

Here is the test result for this case:
```
  Test 'Tax unit with taxsimid 184 from h19.its.csv':
    income_tax@2019: [15631.] differs from 14309.5
        with an absolute margin [1321.5] > 0.01
```

OpenFisca-US and TAXSIM35 agree on AGI ($136,050) and taxable income ($87,050), but disagree on the income tax liability: OpenFisca-US generates a tax of $15,631.00 while TAXSIM35 generates a tax of $14,309.50.  The TAXSIM32 amount is calculated as the sum of two amounts: $1,500 (which is the tax on the $10,000 of long-term capital gains) and $12,809.50 (which is the regular tax on the remaining $77,050 of taxable income).

A glance at the OpenFisca-US code shows that the current version is making an attempt to model the special tax treatment of long-term capital gains and qualified dividends.   But the current logic does not generate the same tax liability as generated by TAXSIM35.
