### ISSUE TITLE
Massachusetts Senior Circuit Breaker Tax Credit

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#935]
Thanks @martinholmer for identifying this gap.

https://www.mass.gov/info-details/massachusetts-senior-circuit-breaker-tax-credit

**Comment by martinholmer** [comment]
@MaxGhenis asked me to provide a couple of test cases for the MA SCB refundable tax credit.   The first case rents, the second owns a house and pays property taxes.

Here is the first case and its test results:
```
# OpenFisca-US test file derived from r21.its.csv and r21.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/14/22) With TCJA

- name: Tax unit with taxsimid 1 from r21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 65
        social_security: 24000
        rent: 12000
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 64
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: MA
  output:
    taxsim_tfica: 0.00
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 0.00
    #taxable_income: 0.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    #income_tax: -2800.00
    ma_income_tax: -670.00

  Test 'Tax unit with taxsimid 1 from r21.its.csv':
    ma_income_tax@2021: [0.] differs from -670.0 
    with an absolute margin [670.] > 0.01
```

Here is the second case and its test results:
```
# OpenFisca-US test file derived from t21.its.csv and t21.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/14/22) With TCJA

- name: Tax unit with taxsimid 1 from t21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 65
        social_security: 24000
        real_estate_taxes: 4000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: MA
  output:
    taxsim_tfica: 0.00
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 0.00
    #taxable_income: 0.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    #income_tax: -1400.00
    ma_income_tax: -1170.00

  Test 'Tax unit with taxsimid 1 from t21.its.csv':
    ma_income_tax@2021: [0.] differs from -1170.0 
    with an absolute margin [1170.] > 0.01
```
